### PR TITLE
Respond to time zone change to update schedule

### PR DESCRIPTION
**Pull request by SeonD**
Fixed issue #235

### CODE REVIEW

**Comment by smichel17** [comment]
Looks good! I just want to test it on my device, then I'll merge.

**Comment by smichel17** [comment]
I also added you as a collaborator, so you can push to branches on this repo if you'd like (`master` is protected, so you'll still need to submit PRs, for now).

**Comment by SeonD** [comment]
Awesome. Thanks much!

**Comment by smichel17** [comment]
Thank ***you!*** For a project this size, receiving a PR is a rare treat :)

**Pull request merged**
